#!/bin/bash
#
###############
# Remove miden-ntx-builder install
##############
svc=miden-ntx-builder

sudo rm -rf "/lib/systemd/system/$svc.service"
sudo rm -rf "/etc/opt/$svc"
sudo deluser "$svc"

sudo systemctl daemon-reload
