#!/bin/bash
#
###############
# Remove miden-node install
##############
svc=miden-node

sudo rm -rf "/lib/systemd/system/$svc.service"
sudo rm -rf "/etc/opt/$svc"
sudo deluser "$svc"

sudo systemctl daemon-reload
