name: Publish Node Docker Image

on:
  release:
    types: [prereleased, released]

  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (E.G. v0.10.0-rc.1, v0.10.0). Corresponding git tag must already exist."
        required: true
        type: string

env:
  version: ${{ inputs.version || github.ref_name }}
  registry: ghcr.io

permissions:
  id-token: write
  contents: write
  packages: write
  attestations: write

jobs:
  publish:
    runs-on:
      labels: "ubuntu-24.04"
    environment: publish-docker
    strategy:
      matrix:
        component: [node]
    name: Publish ${{ matrix.component }} ${{ inputs.version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          ref: ${{ env.version }}
          fetch-depth: 0
          persist-credentials: false

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: GithubActionsSession

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3
        with:
          cache-binary: true

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5
        with:
          push: true
          file: ./bin/${{ matrix.component }}/Dockerfile
          tags: ${{ env.registry }}/0xmiden/miden-${{ matrix.component }}:${{ env.version }}
          cache-from: type=s3,region=${{ secrets.AWS_REGION }},bucket=${{ secrets.AWS_CACHE_BUCKET }},name=miden-${{ matrix.component }}
          cache-to: type=s3,region=${{ secrets.AWS_REGION }},bucket=${{ secrets.AWS_CACHE_BUCKET }},name=miden-${{ matrix.component }},mode=max
